periodics:
  - cron: "05 15 * * 4"  # Run at 15:05 PST (15:05 UTC) Thu
    name: ci-test-infra-autobump-prow
    decorate: true
    extra_refs:
    - org: khulnasoft
      repo: test-infra
      base_ref: master
    spec:
      containers:
      - image: gcr.io/k8s-prow/generic-autobumper:latest
        command:
        - generic-autobumper
        args:
        - --config=config/autobump-config/prow-autobump-config.yaml
        - --signoff
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
      nodeSelector:
        Archtype: "x86"
    annotations:
      description: runs autobumper to create/update a PR that bumps prow to the latest RC without label 'skip-review'
      