apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.10.0
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: khulnasoft-prow-test-infra
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::292999226676:role/khulnasoft-prow-test-infra-loadbalancer-controller
        nodeSelector:
          Archtype: "x86"
        replicaCount: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
